### PR TITLE
fixes for fireauth breaking changes (added multi factor)

### PR DESCRIPTION
**Pull request by cedvdb**

### CODE REVIEW

**Comment by atn832** [comment]
Thanks for the quick fix, @cedvdb!

It's a bit disappointing that the Firebase team would release a breaking change without a major version change.

**Comment by atn832** [comment]
Just uploaded your fix to https://pub.dev/packages/firebase_auth_mocks/changelog#085. Thank you! Fixes #42 and #65.

**Comment by atn832** [comment]
I decided against increasing firebase_auth_mocks's major version, since firebase_auth did not either. This way, when normal people who are unaware of the change get the latest version of firebase_auth, they also get the working version of firebase_auth_mocks.

**Comment by cedvdb** [comment]
> It's a bit disappointing that the Firebase team

Agreed, but I'm more worried about their testing strategy..

**Pull request merged**
